CONFIG_ZMK_SPLIT=y

# Задаем имя, чтобы было легко найти в настройках ПК или телефона
CONFIG_ZMK_KEYBOARD_NAME="SuperMiniSplit"

# Явно включаем Bluetooth
CONFIG_ZMK_BLE=y

# Увеличиваем мощность передатчика для стабильной связи между половинками
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
